import Head from 'next/head'
import Header from './Header.js'
import Card from './Card.js'
import Toast from './Toast.js'
import {primaryArray, secondaryArray } from '../data/data.js'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container py-5'>
        <Header type='h1' name="Overview" />
        <p>If youre visiting this page, youre likely here because youre searching for a random sentence. Sometimes a random word just isnt enough, and that is where the random sentence generator comes into play. By inputting the desired number, you can make a list of as many random sentences as you want or need. Producing random sentences can be helpful in a number of different ways.</p>
        <ul>
          <li>For writers, a random sentence can help them get their creative juices flowing. Since the topic of the sentence is completely unknown, it forces the writer to be creative when the sentence appears. There are a number of different ways a writer can use the random sentence for creativity.</li>

          <li>The most common way to use the sentence is to begin a story. Another option is to include it somewhere in the story. A much more difficult challenge is to use it to end a story. In any of these cases, it forces the writer to think creatively since they have no idea what sentence will appear from the tool.</li>
        </ul>
        <Header type='h1 mt-4' name="Primary Palette" />

        <div className='bg-grey w-100 p-3 rounded'>
          <div className='row row-cols-1 row-cols-md-3 row-cols-md-4 g-3'>
            {primaryArray.map((item, index) => {
              return (
                <div className='col' key={index}>
                  <Header type="h4" name={item.name} />
                  {item.colors.map((el,index) => (
                    <Card key={index} colorName={el.name} hex={el.hex} rgb={el.rgb} />
                  )
                  )}
                </div>
              )
            })}
          </div>
        </div>
        <Header type='h1 mt-4' name="Secondary Palette" />

        <div className='bg-grey w-100 p-3 rounded'>
          <div className='row row-cols-1 row-cols-md-3 row-cols-md-4 g-3'>
            {secondaryArray.map((item, index) => {
              return (
                <div className='col' key={index}>
                  <Header type="h4" name={item.name} />
                  {item.colors.map((el,index) => (
                    <Card key={index} colorName={el.name} hex={el.hex} rgb={el.rgb} />
                  )
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </div>
      <Toast />
    </>
  )
}
